# Copyright DWJ 2024.
# Distributed under the Boost Software License, Version 1.0.
# https://www.boost.org/LICENSE_1_0.txt

# Made with gpt-4o-mini

services:
  items-react:
    image: ghcr.io/${GITHUB_USER:-user}/items-react:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_URL=/items
    ports:
      - "8094:80"
    restart: unless-stopped
    volumes:
      - ./data:/root/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://items-react:80/"]
      interval: 15s
      timeout: 5s
      retries: 5
