# Copyright DWJ 2024.
# Distributed under the Boost Software License, Version 1.0.
# https://www.boost.org/LICENSE_1_0.txt

name: Build and Publish Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USER: ${{ github.repository_owner }}
    steps:
      - name: Env
        run: |
          echo "GITHUB_USER=${GITHUB_USER@L}" >>${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USER --password-stdin

      - name: Build and push all images
        run: |
          docker compose build
          docker compose push
