# Copyright DWJ 2024.
# Distributed under the Boost Software License, Version 1.0.
# https://www.boost.org/LICENSE_1_0.txt

# Made with gpt-4o-mini

services:
  example-example-go:
    image: ghcr.io/${GITHUB_USER:-user}/example-example-go:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1925:1925"
    restart: unless-stopped
    volumes:
      - ./data:/root/data
    environment:
      - SERVICE_TOKEN=$SERVICE_TOKEN
      - EXAMPLE_JWT_PRIVATE_KEY=$EXAMPLE_JWT_PRIVATE_KEY
      - EXAMPLE_JWT_PRIVATE_KEY=$EXAMPLE_JWT_PRIVATE_KEY
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1925/"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    image: golang:1.22.4-alpine
    volumes:
      - ./test:/app
    working_dir: /app
    environment:
      - BASE_URL=http://example-example-go:1925
      - SERVICE_TOKEN=$SERVICE_TOKEN
      - EXAMPLE_JWT_PRIVATE_KEY=$EXAMPLE_JWT_PRIVATE_KEY
      - EXAMPLE_BASE_URL=https://dwidge.online/api
      - DEFAULT_PROFILE_PIC_ID=d3fAu1t
    command: ["go", "test", "./..."]
    depends_on:
      example-example-go:
        condition: service_healthy
